/**
 * CONFIGURACIÓN DE LA INTERFAZ
 * Pegue en DIRECCION_APLICACION la dirección terminada en /exec del despliegue de Google Apps Script.
 */
window.CONFIGURACION_FLOTAS = Object.freeze({
  MODO: 'automatico',
  DIRECCION_APLICACION: 'https://script.google.com/macros/s/AKfycbyj8HforshoFB4340eZgnFu8EcTG2_LWsdRjqoaG--siqR5bQlswiQ6-OWgWVd_Z_VI/exec',
  CLAVE_ALMACENAMIENTO_LOCAL: 'sistema_gestion_flotas_base_local_v3',
  CLAVE_SESION_LOCAL: 'sistema_gestion_flotas_sesion_v3',
  TIEMPO_ESPERA_MILISEGUNDOS: 25000,
  CACHE_MODULOS_MILISEGUNDOS: 60000,
  CACHE_TIEMPO_REAL_MILISEGUNDOS: 4000,
  CACHE_MAXIMA_ANTIGUEDAD_MILISEGUNDOS: 300000,
  PRECARGA_MAXIMA_CONSULTAS: 16,
  INTERVALO_GPS_MILISEGUNDOS: 8000,
  INTERVALO_TIEMPO_REAL_MILISEGUNDOS: 8000,
  INTERVALO_CONEXION_MILISEGUNDOS: 20000,
  INTERVALO_NOTIFICACIONES_MILISEGUNDOS: 15000,
  ANTIGUEDAD_UBICACION_ACTIVA_MILISEGUNDOS: 120000,
  ANTIGUEDAD_CONEXION_ACTIVA_MILISEGUNDOS: 90000,
  RESOLVER_DIRECCIONES: true,
  DIRECCION_GEOCODIFICACION_INVERSA: 'https://nominatim.openstreetmap.org/reverse',
  DIRECCION_BUSQUEDA_DIRECCIONES: 'https://nominatim.openstreetmap.org/search',
  PAIS_BUSQUEDA_DIRECCIONES: 'cl',
  MINIMO_CARACTERES_DIRECCION: 3,
  ESPERA_BUSQUEDA_DIRECCION_MILISEGUNDOS: 450,
  CENTRO_MAPA: [-33.4489, -70.6693],
  NIVEL_ACERCAMIENTO_MAPA: 12
});
